export enum SendMessageError {
  INVALID_INPUT = 'INVALID_INPUT',
  CHAT_SERVICE_ERROR = 'CHAT_SERVICE_ERROR',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  FAILED_TO_SAVE_MESSAGE = 'FAILED_TO_SAVE_MESSAGE',
}
